version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8080"
    environment:
      - SECRET_KEY=django-insecure-!**sh89z2j#)56az5w-%w6-f4@624=bgmj+1cf6$tor&py32s#
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_NAME=herra
      - DB_USER=mog-rn
      - DB_PASSWORD=
      - DB_HOST=db
      - DB_PORT=5432
      - FIREBASE_CREDENTIALS_FILE=herra-21c5a-firebase-adminsdk-hz2so-d3557f22a3.json
      - CSRF_TRUSTED_ORIGINS=https://api.yourdomain.com,https://yourdomain.com,http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000
      - SENDGRID_API_KEY=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
      - DEFAULT_FROM_EMAIL=amos.nyaburi@mog-rn.me
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/libgeos_c.so
      - GEMINI_API_KEY=AIzaSyCMCl570PZSckveSzwgL3yTKpUvyBBy9qw
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      # Mount Firebase credentials
      - ./herra-21c5a-firebase-adminsdk-hz2so-d3557f22a3.json:/app/herra-21c5a-firebase-adminsdk-hz2so-d3557f22a3.json
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=herra
      - POSTGRES_USER=mog-rn
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust  # Allow empty password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume: