# Generated by Django 5.1.2 on 2024-11-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('cycle_length', models.PositiveIntegerField(default=28)),
                ('current_phase', models.CharField(choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], default='menstrual', max_length=20)),
                ('last_period_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.IntegerField(choices=[(1, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Extreme')], null=True)),
                ('energy', models.IntegerField(choices=[(1, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Extreme')], null=True)),
                ('flow_intensity', models.IntegerField(choices=[(1, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Extreme')], null=True)),
                ('pain_level', models.IntegerField(choices=[(1, 'None'), (2, 'Mild'), (3, 'Moderate'), (4, 'Severe'), (5, 'Extreme')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='cycle_tracking.cycletracking')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='cycletracking',
            index=models.Index(fields=['user', 'start_date'], name='cycle_track_user_id_4ceece_idx'),
        ),
        migrations.AddIndex(
            model_name='cycletracking',
            index=models.Index(fields=['user', 'is_active'], name='cycle_track_user_id_17a35c_idx'),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=models.Index(fields=['cycle', 'date'], name='cycle_track_cycle_i_fd91e8_idx'),
        ),
    ]
