# Generated by Django 5.1.2 on 2024-11-12 03:47

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_arrival', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('safe_word', models.CharField(blank=True, max_length=50)),
                ('check_in_interval', models.IntegerField(default=15, help_text='Minutes between check-ins')),
                ('last_check_in', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('check_in', 'Wellness Check'), ('location', 'Location Share'), ('medical', 'Medical Alert'), ('journey', 'Journey Tracking')], default='check_in', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('responded', 'Responded')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('battery_level', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='safety.journeytracking')),
            ],
        ),
        migrations.CreateModel(
            name='SafeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField()),
                ('radius', models.IntegerField(default=100, help_text='Safe zone radius in meters')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide this location from main view')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery_level', models.IntegerField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_type', models.CharField(choices=[('emergency', 'Emergency Contact'), ('wellness', 'Wellness Coach'), ('friend', 'Friend')], default='friend', max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='safety_emer_user_id_32b211_idx'), models.Index(fields=['phone_number'], name='safety_emer_phone_n_d88bdc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journeytracking',
            index=models.Index(fields=['user', 'is_active'], name='safety_jour_user_id_146e68_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['user', 'created_at'], name='safety_emer_user_id_6f5941_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status'], name='safety_emer_status_6d9604_idx'),
        ),
        migrations.AddIndex(
            model_name='safelocation',
            index=models.Index(fields=['user', 'is_active'], name='safety_safe_user_id_7c93a2_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', 'timestamp'], name='safety_user_user_id_3340e4_idx'),
        ),
    ]
